version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        - FAST_DEV=true
    container_name: poliverai-backend
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=src
    ports:
      - "8000:8000"
    command: ["/opt/venv/bin/python", "-m", "uvicorn", "poliverai.app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000", "--app-dir", "/app/src"]
    volumes:
      - ./:/app

  frontend_dev:
    image: node:20-alpine
    container_name: poliverai-frontend-dev
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    env_file:
      - ./.env
    environment:
      - VITE_API_URL=http://localhost:8080
    command: ["sh", "-c", "yarn install --frozen-lockfile || true && yarn dev --host 0.0.0.0 --port 5173"]
    ports:
      - "5173:5173"
    depends_on:
      - backend

  proxy:
    image: nginx:stable-alpine
    container_name: poliverai-proxy
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - frontend_dev
      - backend

# Usage: docker compose -f docker-compose.dev.yml up --build
