version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.deployer
      args:
        - FAST_DEV=true
    container_name: poliverai-backend
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=src
      # Connect to local Mongo service started below
      # Use local MongoDB for development so the backend doesn't attempt to
      # reach MongoDB Atlas (avoids TLS issues when developing locally).
      # - MONGO_URI=mongodb://mongo:27017/poliverai
      # Ensure Google ADC and our code use the mounted key.json absolute path
      - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json
      - POLIVERAI_GCS_CREDENTIALS_JSON=/app/key.json
      # Default user id used when no authenticated user is present (dev only)
      - POLIVERAI_DEFAULT_USER_ID=d8faff07-97cb-42c6-aa42-cc002ba4584f
    ports:
      - "8000:8000"
    command: ["/opt/venv/bin/python", "-m", "uvicorn", "poliverai.app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000", "--app-dir", "/app/src"]
    volumes:
      - ./:/app

  # mongo:
  #   image: mongo:6.0
  #   container_name: poliverai-mongo
  #   restart: unless-stopped
  #   volumes:
  #     - poliverai-mongo-data:/data/db
  #   environment:
  #     - MONGO_INITDB_DATABASE=poliverai

  frontend_dev:
    image: node:20-alpine
    container_name: poliverai-frontend-dev
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    env_file:
      - ./.env
    environment:
      - VITE_API_URL=http://localhost:8080
    command: ["sh", "-c", "yarn install --frozen-lockfile || true && yarn dev --host 0.0.0.0 --port 5173"]
    ports:
      - "5173:5173"
    depends_on:
      - backend

  proxy:
    image: nginx:stable-alpine
    container_name: poliverai-proxy
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - frontend_dev
      - backend

# Usage: docker compose -f docker-compose.dev.yml up --build

# volumes:
#   poliverai-mongo-data:
