# Resolve react_native_pods.rb from either app-local or workspace-level node_modules.
react_native_pods_rb = File.expand_path('../node_modules/react-native/scripts/react_native_pods.rb', __dir__)
unless File.exist?(react_native_pods_rb)
  react_native_pods_rb = File.expand_path('../../../node_modules/react-native/scripts/react_native_pods.rb', __dir__)
end

require react_native_pods_rb

platform :ios, '15.4'
prepare_react_native_project!

project 'PoliverAI', {
  'Debug' => :debug,
  'DebugExperimental' => :debug,
  'Release' => :release,
}

new_arch_enabled = ENV.fetch('RCT_NEW_ARCH_ENABLED', '0') == '1'
ENV['RCT_NEW_ARCH_ENABLED'] = new_arch_enabled ? '1' : '0'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'PoliverAI' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :new_arch_enabled => new_arch_enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
